"""
VARUNA Backend — CF Conventions metadata service.

Generates CF-1.8 compliant metadata attributes for VARUNA ocean variables.
This ensures interoperability with standard oceanographic tools (Panoply,
xarray, ERDDAP, etc.).

Ref: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html
"""
from __future__ import annotations

from datetime import datetime, timezone

from ..schemas import CFGlobalMetadata, CFVariableMetadata


# ── per-variable CF metadata ─────────────────────────────────────────

VARIABLE_CF_METADATA: dict[str, CFVariableMetadata] = {
    "sst_c": CFVariableMetadata(
        standard_name="sea_surface_temperature",
        long_name="Sea Surface Temperature",
        units="degC",
        valid_min=-2.0,
        valid_max=45.0,
    ),
    "current_u_ms": CFVariableMetadata(
        standard_name="eastward_sea_water_velocity",
        long_name="Eastward Sea Water Velocity (Zonal Current)",
        units="m s-1",
        valid_min=-5.0,
        valid_max=5.0,
    ),
    "current_v_ms": CFVariableMetadata(
        standard_name="northward_sea_water_velocity",
        long_name="Northward Sea Water Velocity (Meridional Current)",
        units="m s-1",
        valid_min=-5.0,
        valid_max=5.0,
    ),
    "wave_height_m": CFVariableMetadata(
        standard_name="sea_surface_wave_significant_height",
        long_name="Significant Wave Height",
        units="m",
        valid_min=0.0,
        valid_max=25.0,
    ),
    "salinity": CFVariableMetadata(
        standard_name="sea_water_practical_salinity",
        long_name="Practical Salinity",
        units="1e-3",
        valid_min=0.0,
        valid_max=42.0,
    ),
    "chlorophyll": CFVariableMetadata(
        standard_name="mass_concentration_of_chlorophyll_a_in_sea_water",
        long_name="Chlorophyll-a Concentration",
        units="mg m-3",
        valid_min=0.0,
        valid_max=100.0,
    ),
}


def get_variable_metadata(variable: str) -> CFVariableMetadata | None:
    """Return CF metadata for a known variable, or None."""
    return VARIABLE_CF_METADATA.get(variable)


def get_all_variable_metadata() -> dict[str, CFVariableMetadata]:
    """Return CF metadata for all known variables."""
    return VARIABLE_CF_METADATA.copy()


def get_global_metadata() -> CFGlobalMetadata:
    """Return CF-1.8 global attributes for the current dataset."""
    return CFGlobalMetadata(
        history=f"Generated by VARUNA backend at {datetime.now(timezone.utc).isoformat()}",
    )


def build_cf_headers() -> dict[str, str]:
    """
    Build HTTP headers carrying CF Conventions metadata.

    These are attached to REST API responses so downstream tools
    can discover the data's CF compliance without parsing the body.
    """
    return {
        "X-CF-Conventions": "CF-1.8",
        "X-CF-Institution": "INCOIS / SIH Team Hudson Hackers",
        "X-CF-Source": "VARUNA Graph Fusion Engine",
        "X-CF-Title": "VARUNA Fused Ocean State",
    }
